### ISSUE TITLE
Support more repository values

### ISSUE THREAD

**Issue by exploids** [maxstrauch/lisense#12]
It looks like `repoFragmentToUrl` cannot handle a lot of [valid](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#repository) repository fragments. For example the following fragments are valid, but aren't recognized by lisense and result in `repoBaseUrl` being `null`:

```json5
"lodash/lodash"
// ➡️ app:repoFragmentToUrl Can't handle:  lodash/lodash
```

```json5
"https://github.com/Rich-Harris/vlq"
// ➡️ app:repoFragmentToUrl Can't handle:  https://github.com/Rich-Harris/vlq
```

```json5
"git://github.com/isaacs/rimraf.git"
// ➡️ app:repoFragmentToUrl Can't handle:  git://github.com/isaacs/rimraf.git
```

```json5
{"type":"git","url":"git@github.com:tsertkov/exec-sh.git"}
// ➡️ app:repoFragmentToUrl Can't handle GIT reference:  git@github.com:tsertkov/exec-sh.git
```

**Comment by maxstrauch** [comment]
@exploids I'm sorry, I didn't got noticed about your issue and just saw it right now :-/

**Comment by maxstrauch** [comment]
@exploids I finally worked on your request and add a lot of parsing logic for SCM "strings" and license extraction. For example the following SCM strings are recognized (left=input, right=output):

    github:user/repo/goo.git                                                --> https://github.com/user/repo/goo.git
    gist:0bce1161cfd2aa91ae7cad9abb42c342                                   --> https://gist.github.com/0bce1161cfd2aa91ae7cad9abb42c342
    bitbucket:multicoreware/x265_git                                        --> https://bitbucket.org/multicoreware/x265_git/
    gitlab:gitlab-org/gitlab.git                                            --> https://gitlab.com/gitlab-org/gitlab.git
    npm/lodash                                                              --> https://www.npmjs.com/package/lodash
    git@github.com:tsertkov/exec-sh.git                                     --> https://github.com/tsertkov/exec-sh.git
    git://github.com/isaacs/rimraf.git                                      --> https://github.com/isaacs/rimraf.git
    git+ssh://github.com/Azure/azure-sdk-for-js.git                         --> https://github.com/Azure/azure-sdk-for-js.git
    git+ssh://git@github.com/Azure/azure-sdk-for-js.git                     --> https://github.com/Azure/azure-sdk-for-js.git
    git+https://github.com/facebook/react.git                               --> https://github.com/facebook/react.git
    github.com/megawac/MutationObserver.js                                  --> https://github.com/megawac/MutationObserver.js
    https://vadimdez@github.com/VadimDez/ng2-pdf-viewer.git/blob/master/    --> https://github.com/VadimDez/ng2-pdf-viewer.git/blob/master/

I hope this fits your need!
